---
- name: Create Google Cloud Instance
  hosts: localhost
  become: yes
  vars:
    machine_name: master1
    google_project_id: gentle-bot-466204-d3
    # location where you put the service account.json file
    service_account_path: /home/dev-user/deopvs_deployment_lesson/ansible_practices/iaC2/playbooks/google_services_account.json
    ssh_public_key_path: /home/dev-user/.ssh/id_ed25519.pub
  tasks:
    - name: Slurp the local public key
      slurp:
        src: "{{ ssh_public_key_path }}"
      register: ssh_pub_key
    - name: install Pip
      apt:
        name:
          - python3-requests
          - python3-google-auth
        state: present
    - name: Create GCP instance
      google.cloud.gcp_compute_instance:
        name: "{{machine_name}}"
        machine_type: "e2-medium"
        zone: "us-central1-a"
        project: "{{google_project_id}}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ service_account_path }}"
        state: present
        metadata:
          ssh-keys: "dev-user:{{ ssh_pub_key['content'] | b64decode }}"
          startup-script: |
            #!/bin/bash
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install fish -y
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
              disk_size_gb: 15
              disk_type: "pd-standard"
        network_interfaces:
          - network:
              selfLink: "projects/{{google_project_id}}/global/networks/default"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - http-server
            - https-server
      register: gcp_instance
      when: true
    - name: Write gcp_instance into json file
      copy:
        content: "{{ gcp_instance }}"
        dest: "./gcp_instance.json"
      when: true
    - name: Generate Inventory
      template:
        src: ../templates/gcp-inventory-template.j2
        dest: ../inventory/hosts.ini
# ansible-playbook playbooks/launch-gcp-instance.yaml