---
- name: Setup NFS Server
  hosts: localhost
  become: yes

  vars:
    nfs_remote_dir: /srv/nfs_shared
    # nfs_client_ip1: 10.128.0.6
    # nfs_client_ip2: 10.128.0.7
    nfs_client_ip3: 10.128.0.8
  tasks:
    - name: Update APT caches
      apt:
        update_cache: yes
    - name: Create Directory to used
      file:
        path: "{{ nfs_remote_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: "0777"
    # configuration inside /etc/exports ( tell which clients can use  it)
    - name: Write Config on /etc/exports
      lineinfile:
        path: /etc/exports
        # line: " {{ nfs_remote_dir }} *(rw,sync,no_subtree_check,no_root_squash)"
        line: " {{ nfs_remote_dir }} {{nfs_client_ip3}}(rw,sync,no_subtree_check,no_root_squash)"
        state: present
        create: yes
    - name: Apply Configuration
      command: exportfs -ra
    - name: Restart NFS Kernel Service
      systemd:
        name: nfs-kernel-server
        enabled: true
        state: restarted