- name: Update Apt Cache 
  apt: 
    update_cache: true 
- name: Install Nginx 
  apt: 
    name: nginx 
    state: absent 
# only for learning , because docker_compose module is repreciated
# docker_compose_v2
- name: Uninstall Docker 
  apt:
    name: docker 
    state: absent 
- name: Uninstall Docker COmpose 
  apt: 
    name: docker-compose 
    state: absent 
- name: Uninstall fish shell 
  apt: 
    name: fish 
    state: absent 