# services ( wordpress , mysql )
services:
  wordpress-svc: 
    image: wordpress:latest
    container_name: wordpress_cont 
    environment:
    - WORDPRESS_DB_HOST=mysql-db
    - WORDPRESS_DB_USER=${DB_USER}
    - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    - WORDPRESS_DB_NAME=${DB_DATABASE}
#Add these lines for debugging:
    - WORDPRESS_DEBUG=1
    - WORDPRESS_DEBUG_LOG=/dev/stderr
    - WORDPRESS_DEBUG_DISPLAY=0
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - wordpress_network
    restart: always
    ports:
      - "3000:80"
  mysql-db:
    container_name: mysql_cont 
    image: mysql 
    restart: always
    ports:
      - 8080:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_USER=${DB_USER:-testinguser}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - wordpress_network
# backup date from containers to these volume 
volumes:
  wordpress_vol: 
  mysql_vol: 
networks:
  wordpress_network: 


# docker compose up -d 
# network: ip:port 
