- name: Update Apt Cache 
  apt: 
    update_cache: true 
- name: Install Nginx 
  apt: 
    name: nginx 
    state: present 
# only for learning , because docker_compose module is repreciated
# docker_compose_v2
- name: Install Docker 
  apt:
    name: docker 
    state: present 
- name: Install Docker Compose 
  apt: 
    name: docker-compose 
    state: present 
- name: Install fish shell 
  apt: 
    name: fish 
    state: present 
- name: Append user to docker group 
  user: 
    name: dev-user # get the ansible_user 
    groups: docker 
    append: true 