---
- name: Run Media Service Spring Boot
  hosts: server2
  become: true
  vars:
    image_name: "69966/springgradleimg:1.1.1"
  tasks: # <--- ENSURE THIS LINE IS PRESENT AND CORRECTLY INDENTED (2 spaces from 'vars:')
    # Running compose on worker2 by copy
    - name: Copy docker compose file from local
      copy:
        src: /home/dev-user/my_ansible/docker-compose.yaml
        dest: /opt/docker-compose.yaml
    - name: Run docker compose command on opt directory
      command: "docker-compose up -d "
      args:
        chdir: /opt
    # IMPORTANT: Also, double-check that you've correctly updated the following task
    # (if you intend to use it and uncomment 'when: false')
    - name: Using docker_compose_v2 module
      community.docker.docker_compose_v2: # v2
        project_name: spring-boot-media-api
        definition:
          services:
            spring-media-api:
              image: "{{ image_name }}"
              container_name: spring_cont
              restart: always
              volumes:
                - "/mnt/nfs_shared/images:/app/src/main/resources/images"
              ports:
                - "8080:8080"
      # REMEMBER: If you want this task to actually run, remove or change 'when: false' to 'when: true'
      # when: false