- name: Install Common Service Playbook
  hosts: myserver
  become: yes # create user, sudo apt install ....
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present  # present = install , absent = uninstall
    - name: Install docker
      apt:
        name: docker
        state: present
      ignore_errors: true
    - name: Install docker compose
      apt:
        name: docker-compose
        state: present
    - name: install fish shell
      apt:
        name: fish
        state: present
    - name: Install neofetch
      apt:
        name: neofetch
        state: present
    - name: Add current user to docker group
      user:
         name: dev-user
         groups: docker
         append: true